### ISSUE TITLE
What is this project about?

### ISSUE THREAD

**Issue by aivarannamaa** [beardad1975/thonny-postit#1]
Hi!

I'm Thonny's main author. I found your plug-in by accident. Can you please explain in few words what this plug-in does? The `images` directory looks really interesting :)

**Comment by beardad1975** [comment]
Hi
    I  am a elementary school teacher in Taiwan .   Thonny-postit   is  a
plug-in I wrote for 10 ~ 15 year-old  student.
It's  kind of mix of  clipboard  and  block.  It's hard to express the
idea  by my poor english.  So I  make a  small Demo  film.

https://youtu.be/SByvSIEDSi8

It's based on the wonderful Thonny Project.  Thanks a lot to you .  This
Plug-in is still in th early development stage  , and many UI text
is just for my hometown language now (no plans for internationalization yet
) . I  will try  to make it better and fun .  I wish it will be a bridge
from
Scratch to Python.

By the way , I just wonder why there is no tools button  like   Copy, Cut,
Paste, Undo.  That's why  I  made them in the plug-in.

                                           beardad1975  ( Wen-Hung , Chang)


Aivar Annamaa <notifications@github.com> 於 2020年6月11日 週四 下午3:20寫道：

**Comment by beardad1975** [comment]
I didn't write the README yet.  I'll  do it  when I figure something out ( Maybe  README of english and chinese )

**Comment by aivarannamaa** [comment]
Thanks, the demo looks really promising!

I also wanted to create a bridge from Scratch to Python but I never had time for this. I hope you will succeed!

By the way, have you seen https://edublocks.org/ ? Maybe you can get ideas from there.

**Comment by beardad1975** [comment]
Thank you for tje advice . I  had tried  edublocks  before. It's really good.  But it is not enough for me.There are some reasons that I didn't use it.
- Translations  to local language (and also the balance between python keyword and translation) 
- Still lack of common text edit skill training
- Web Environment has many limitations ( a lot different from origin python) 

I also tried Mu .  But I still believe Thonny is the tool that I want to build on top.
